import { Metadata } from "next";
import Link from "next/link";

import { getAllPosts } from "@/lib/posts";
import { Projects } from "@/config/projects";
import { testimonials } from "@/config/testimonials";

export const metadata: Metadata = {
  title: "Site Index",
  robots: { index: false, follow: false }, // keep out of search engines
};

const staticSections = [
  {
    heading: "Main Navigation",
    routes: [
      { path: "/",           label: "Home",       notes: "Hero, stats, projects preview, testimonials, experience preview" },
      { path: "/projects",   label: "Projects",   notes: "AI and other project showcases and detailed case-study pages" },
      { path: "/experience", label: "Experience", notes: "Timeline, education, bio, recommendation letter lightbox" },
      { path: "/skills",     label: "Skills",     notes: "Tag cloud of technical and creative skills" },
      { path: "/blog",       label: "Blog",       notes: "MDX blog posts listing" },
      { path: "/contact",    label: "Contact",    notes: "Google Form + Upwork / LinkedIn connect cards" },
    ],
  },
  {
    heading: "Secondary Pages",
    routes: [
      { path: "/testimonials", label: "Testimonials", notes: `All ${testimonials.length} testimonials in 3-col grid. Linked from homepage ghost button.` },
      { path: "/writing",      label: "Writing",      notes: "Full writing portfolio — music, health, solar, business, crypto" },
      { path: "/music",        label: "Music",        notes: "Audio player (7 tracks), Spotify embeds, YouTube covers grid" },
    ],
  },
  {
    heading: "System / Reference",
    routes: [
      { path: "/site-map",    label: "Site Index",  notes: "This page. Not in nav, not indexed." },
      { path: "/sitemap.xml", label: "XML Sitemap", notes: "Auto-generated by app/sitemap.ts" },
    ],
  },
];

export default function SiteIndexPage() {
  const posts = getAllPosts();

  const projectSection = {
    heading: "Project Case Studies (auto-updated from config/projects.ts)",
    routes: Projects.map((project) => ({
      path: `/projects/${project.id}`,
      label: project.companyName,
      notes: project.role ?? project.shortDescription.substring(0, 50) + "...",
    })),
  };

  const blogSection = {
    heading: "Blog Posts (auto-updated from content/posts/)",
    routes: posts.map((post) => ({
      path: `/blog/${post.slug}`,
      label: post.title ?? post.slug,
      notes: post.date ?? "No date",
    })),
  };

  const sections = [
    staticSections[0], // Main Nav
    projectSection,    // Projects
    staticSections[1], // Secondary
    blogSection,       // Blog
    ...staticSections.slice(2), // System
  ];

  return (
    <div className="container py-12 max-w-3xl mx-auto space-y-10">
      <div className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight">Site Index</h1>
        <p className="text-sm text-muted-foreground">
          Personal reference — all pages and routes at a glance. Not linked from nav, not indexed by search engines.
        </p>
      </div>

      {sections.map((section) => (
        <section key={section.heading} className="space-y-3">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground border-b border-border pb-1">
            {section.heading}
          </h2>
          <table className="w-full text-sm">
            <tbody className="divide-y divide-border">
              {section.routes.map((route: { path: string; label: string; notes: string }) => (
                <tr key={route.path}>
                  <td className="py-2 pr-4 w-52 align-top">
                    <Link
                      href={route.path}
                      className="font-medium text-foreground hover:text-primary transition-colors"
                    >
                      {route.label}
                    </Link>
                  </td>
                  <td className="py-2 pr-4 w-48 align-top font-mono text-[11px] text-muted-foreground break-all">
                    {route.path}
                  </td>
                  <td className="py-2 align-top text-muted-foreground">
                    {route.notes}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ))}
    </div>
  );
}
